#! /usr/dash

# Basic info
ROOT=`df -Ph | grep xvda1 | awk '{print $4}' | tr -d '\n'`

# System load
MEMORY1=`free -t -m | grep Total | awk '{print $3" MB";}'`
MEMORY2=`free -t -m | grep "Mem" | awk '{print $2" MB";}'`
LOAD1=`cat /proc/loadavg | awk {'print $1'}`
LOAD5=`cat /proc/loadavg | awk {'print $2'}`
LOAD15=`cat /proc/loadavg | awk {'print $3'}`

echo "\033[0;92m"'Welcome to your wp-puphpet.io WordPress development server'"\033[0m"

cat << EOF

Memory: `free -m | head -n 2 | tail -n 1 | awk {'print $2'}`M	CPU Load: `cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3}'`
Swap: `free -m | tail -n 1 | awk {'print $2'}`M	Free Memory: `free -m | head -n 2 | tail -n 1 | awk {'print $4'}`M
Disk: `df -h / | awk '{ a = $2 } END { print a }'`	Free Swap: `free -m | tail -n 1 | awk {'print $4'}`M
Free Disk: `df -h / | awk '{ a = $2 } END { print a }'`

Public Address: `ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk      '{print $1}'`
Cloud Address: `ifconfig eth1 | grep "inet addr" | awk -F: '{print    $2}' | awk '{print $1}'`

Distro: `lsb_release -s -d` with `uname -r`	

EOF
 